services:

  postgres:
    image: postgres:16
    container_name: finpilot-postgres
    environment:
      POSTGRES_DB: finpilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: finpilot-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./Backend
    container_name: finpilot-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finpilot
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_MODEL: qwen3:1.7b

    depends_on:
      - postgres
      - ollama

    restart: unless-stopped


volumes:
  postgres_data:
  ollama_data: